### ISSUE TITLE
FFMPEG git patches for VVC decoding

### ISSUE THREAD

**Issue by alexdns1** [MartinEesmaa/VVCEasy#24]
https://patchwork.ffmpeg.org/project/ffmpeg/list/?series=7922

Now that there are patches for VVC decoding coded by spin digital do you think you can implement them in your vvceasy to skip the vvcdec completely ?

**Comment by MartinEesmaa** [comment]
Hello, @alexdns1! Thank you for replying with me.

Yes, I can implement some patches into my FFmpeg repository. 

Before I do that, these patches were made from FFmpeg for 5.1+ version, because it may not work for FFmpeg outdated commits from my current repository, so I have to back up, delete, start over and commit new changes to my FFmpeg new refresh forked repository.

I can skip new vvdec patch from Spin Digital (Thomas Siedel) and keep old vvdec patch from tbiat. Only new vvdec patch did not work for bitstream files only, others were worked fine like mp4 mux after some tbiat's patches. I will test old vvdec patch soon...

- Martin Eesmaa

**Comment by MartinEesmaa** [comment]
Only my custom repository works with old FFmpeg version to play & encode VVC raw bitsreams only, but newest version of FFmpeg-VVC does not play or encode (.266,.vvc,.h266 file type) to raw VVC bitstreams only. Also, I tried test new vvenc patch into my current FFmpeg repository, but still works. I will release one patch to my custom FFmpeg repository.

- Martin Eesmaa

**Comment by MartinEesmaa** [comment]
The vvenc commit is now in my FFmpeg repository: https://github.com/MartinEesmaa/FFmpeg-FixVVC/commit/6622bf8e566a7656bbae306d336f2f89c3462381

Since, its new codes came in late 2022 from FFmpeg patchwork, I decided to release FFmpeg latest version for up to 5.1 version. 

Here is Windows build of FFmpeg VVCEasy: https://github.com/MartinEesmaa/VVCEasy/commit/a45c38a73227d7428c865f80a4cf7982a49e8909

I leave your issue here until you close the issue after it's solved.

- Martin Eesmaa

**Comment by MartinEesmaa** [comment]
I'll close the issue after no responses for months. Feel free to reopen the issue, I'll try make new FFmpeg build.
