### ISSUE TITLE
vvencapp: The encoding process stopped at the beginning.

### ISSUE THREAD

**Issue by Niotferdi** [MartinEesmaa/VVCEasy#34]
**Describe the bug**
vvencapp: The encoding process stopped at the beginning.

**To Reproduce**
Run the command `ffmpeg -i cut_test.mkv -pix_fmt yuv420p -f yuv4mpegpipe - | vvencapp --y4m -i - --preset medium --qp 35 -o converted.266`
The frame counter stops at a certain number (sometimes - 20, 40, 17, 23, 35), the file size specified in `-o` is 0 bytes and does not grow. No coding occurs.

**Expected behavior**
I see how the counter of processed frames increases in the cmd output, and how the size of the output file increases.

**Desktop (please complete the following information):**
Windows 10

**Comment by Niotferdi** [comment]
Tested it. I can use `ffmpeg -i cut_test.mkv -pix_fmt yuv420p -f yuv4mpegpipe - | vvencapp --y4m -i - -r 24000/1001 -s 1920x1080 --preset medium --qp 35 -o converted.266` command, but I can't use `ffmpeg -i cut_test.mkv -pix_fmt yuv420p -f yuv4mpegpipe - | vvencapp --y4m -i - -r 24000/1001 -s 1920x1080 --preset medium --qp 10 -o converted.266.` HOWEVER, the only difference between them is --qp - 10 versus 35. 34 can already be used, like 35. But 20 cannot. Although valid values are from 0 to 63. What's the problem?

**Comment by MartinEesmaa** [comment]
Hi, @Niotferdi!

I don't know why the problem caused for the frame counter using some QP numbers, that's weird :/.
Maybe you can give me a sample matroska file to me via GitHub or send me email martin.eesmaa@protonmail.com?

Also, I updated vvenc build if you want to try it again. https://github.com/MartinEesmaa/VVCEasy/commit/1662a7784d9b9d624c2128de7d1ae5dba5e0f76b

- Martin Eesmaa

**Comment by Niotferdi** [comment]
During this time I conducted a couple of tests. `--qp` works fine, only `--refreshsec` with any value does not work, I use `--intraperiod` instead. I also need to specify `-r 24000/1001 -s 1920x1080`, otherwise nothing will happen.

However, copying video properties into cmd is not a problem for me. I noticed that keyframes need to be set manually, chosen at random. By randomly selecting a lucky number of frames, I will get a smaller file size. Numbers both larger and smaller than happy ones inflate the file size. Also, by specifying too high a value, frame backstep rewind does not work in my mpv.
And about `fps`. You said that when dividing one number by another, you need to specify `--fps` instead of `-r`. It turns out I made a mistake. And what happened to my video?

My video is an anime segment. I don’t know if publishing it freely on the Internet is considered piracy (even publishing a 60-second segment). This is a clip from the first episode of Ergo Proxy to avoid spoilers.

**Comment by MartinEesmaa** [comment]
Hi, @Niotferdi! Sorry for long wait response!

Anyway...

> only --refreshsec with any value does not work, I use --intraperiod instead.

This is maybe advanced argument options, but you're still welcome to use it using intraperiod for any custom value.

> By randomly selecting a lucky number of frames, I will get a smaller file size.

Randomly selecting number of frames like intraperiod, let's say 24 and you got smaller file size, but it can be little more lossy without automatic. Every 24 frames goes on loop until EOF (end of file). 

First frame of number one is intra, between second and twenty-third is P-frames and twenty-fourth frame will be B-frame.
Twenty-fifth of frame is intra again. So that goes again with custom specified number of intraperiod. But if you put less than 24 for your intraperiod command (example 10), it will be bigger file size with higher quality.

> You said that when dividing one number by another, you need to specify --fps instead of -r. It turns out I made a mistake. And what happened to my video?

Oh yeah... sorry for your mistake and happened to your video, so you need to specify `--fps` argument command to make it correct for your 23.976 FPS video copy, otherwise it makes mess for out of sync.

```
  -r,   --framerate [60]           temporal rate (framerate numerator) e.g. 25,30, 30000, 50,60, 60000
        --framescale [1]           temporal scale (framerate denominator) e.g. 1, 1001
        --fps [60/1]               framerate as int or fraction (num/denom)
        --tickspersec [27000000]   ticks per second for dts generation, (1..27000000, -1: ticks per frame=1)
```

> My video is an anime segment. I don’t know if publishing it freely on the Internet is considered piracy (even publishing a 60-second segment). This is a clip from the first episode of Ergo Proxy to avoid spoilers.

Right, thanks for the info that you gave me example that you're trying to encode!

If you have any questions or issues, let me know. Thanks! :)

Regards,
Martin Eesmaa

**Comment by MartinEesmaa** [comment]
I had to close the issue due to the inactivity with no response for one year, so feel free to reopen the issue again if you have still issue on it. Sorry about this has to close the issue.

- Martin Eesmaa
