### ISSUE TITLE
Question about a new type of audio encoding.

### ISSUE THREAD

**Issue by jiangzemin-xudamin** [MartinEesmaa/VVCEasy#38]
Hi Martin, I recently noticed that you've added some support for audio encoding programs to the VVCEASY project on Github. I have a couple of questions to say:

1. can these new audio encoding programs surpass OPUS encoding in terms of compression efficiency?

2. is it possible to add Facebook's "EncodeC" encoding to FFMPEG?

https://github.com/facebookresearch/encodec

3. Do you plan to support these new encoding formats in your modified MPV player?

**Comment by MartinEesmaa** [comment]
Hi, @jiangzemin-xudamin!

Thank you for asking three questions to me. I will answer your questions:

1. Well it may can surpass OPUS encoding by new audio encoding programs like xHE-AAC or other improved encoder programs.
2. It requires implementation to FFmpeg to write encodec decoder using C programming language, so that's hard to write on it for me, but I'm not good using C advanced programming skills and have to learn it by myself. You may need to create issue to encodec repository, if someone can make encodec implementation to FFmpeg for your request.
3. I'm not sure if I can plan new encoding formats to my modified MPV player, but I might find out later if I can still add for it.

Thank you! Feel free to reply me if you like! :)

Regards
- Martin Eesmaa

**Comment by jiangzemin-xudamin** [comment]
Thanks for your answer, Martin
This is an audio test about MP3, OPUS, Lyra-v2, EnCodec, EVS, SoundStream:

https://ai.honu.io/papers/encodec/samples.html

In terms of sound quality at the same bitrate, my personal ranking is: EnCodec>SoundStream>EVS>Lyra-v2>OPUS>MP3.
